Added global error handler to Memcached adapter to handle connection errors gracefully
DanielHreben/sequelize-transparent-cache pull request #77
Opened 2020-09-07 20:29 UTC by mvlasovatl

Hello!
My app is running on AWS and connects to Amazon ElastiCache. Sometimes AWS has connectivity issues or node crushed or it just decides to restart Memcached cluster. If during this period my app calls any method from the cache wrapper like the following, Memcached client throws an error and the whole request processing interrupts.
```javascript
// Load user from cache
const user = await User.cache().findByPk(1); // Error: Memcached connection error!

// Update in db and cache
await user.cache().update({ // Error: Memcached connection error!
  name: 'Vikki'
})
```
It would be great if there was a possibility to swallow a connection error in that case and fall back to DB queries.
My PR contains this enhancement. Please review.
The change is backward-compatible and activated on demand only by passing a handler to wrapper constructor. Current and new behavior are covered with tests, all tests are passing locally.

2020-09-10 15:32 UTC, utluiz approved these changes
Thanks, Mykhailo! Looks good (from a consumer perspective).

2020-09-11 16:15 UTC, DanielHreben requested changes

2020-09-11 16:15 UTC, DanielHreben commented on packages/sequelize-transparent-cache-memcached/src/memcached-adaptor.js
>      return new Promise((resolve, reject) => {
mb just add `.catch` after this `new Promise()` instead of try\catch?

2020-09-11 16:15 UTC, DanielHreben commented on packages/sequelize-transparent-cache-memcached/src/memcached-adaptor.js
> +        resolve(this.errorHandler(error, operation, key))
should error handler also be an async function?

2021-03-29 11:48 UTC, mvlasovatl commented
After discussion with a team, we concluded that these changes won't solve the actual issue we faced. I close this PR in favor of more essential changes in project code.

2021-03-29 11:48 UTC, closed without merging